CC = g++
LIBS = 
INCLUDE = 
OPTS          = -o
CLASS_BUILD   = -c
DEBUG         = -Wall -g

	
test_file:
	$(CC) $(OPTS) main ../lib/File.h TestFile.cpp
	@cp main ../bin/TestFile
	@rm main
	@echo "Build"
	

